NAME=NuiLib

# - ROOT DIRECTORIES -
BIN_DIR=Bin/
INC_DIR=Include/
LIB_DIR=Lib/
SRC_DIR=Src/

# - SRC DIRECTORIES -

CORE_DIR=$(SRC_DIR)NuiLib/
KINECT_MS_DIR=$(SRC_DIR)NuiLib-Kinect-MS/
TEST_DIR=$(SRC_DIR)Test/
DEMO_SLIDESHOW_DIR=$(SRC_DIR)SlideshowDemo/
DEMO_MOVEMENT_DIR=$(SRC_DIR)MovementDemo/
DEMO_MANIPULATION_DIR=$(SRC_DIR)ManipulationDemo/
UNITTEST_DIR=$(SRC_DIR)UnitTests/

# - CORE FILES -
CORE_SOURCES=$(CORE_DIR)$(NAME)-API.cpp $(CORE_DIR)$(NAME)-Vectors.cpp $(CORE_DIR)$(NAME)-Scalars.cpp $(CORE_DIR)$(NAME)-Conditions.cpp $(CORE_DIR)$(NAME)-Processing.cpp $(CORE_DIR)$(NAME)-Extendable.cpp
CORE_OBJECTS=$(patsubst $(CORE_DIR)%.cpp, $(CORE_DIR)%.o, $(CORE_SOURCES))

# - KINECT MS FILES -
KINECT_MS_SOURCES=$(KINECT_MS_DIR)$(NAME)-Kinect-MS.cpp
KINECT_MS_OBJECTS=$(patsubst $(KINECT_MS_DIR)%.cpp, $(KINECT_MS_DIR)%.o, $(KINECT_MS_SOURCES))

# - DEMO - SLIDESHOW FILES -
DEMO_SLIDESHOW_SOURCES=$(DEMO_SLIDESHOW_DIR)main.cpp
DEMO_SLIDESHOW_OBJECTS=$(patsubst $(DEMO_SLIDESHOW_DIR)%.cpp, $(DEMO_SLIDESHOW_DIR)%.o, $(DEMO_SLIDESHOW_SOURCES))

# - DEMO - MOVEMENT FILES -
DEMO_MOVEMENT_SOURCES=$(DEMO_MOVEMENT_DIR)main.cpp
DEMO_MOVEMENT_OBJECTS=$(patsubst $(DEMO_MOVEMENT_DIR)%.cpp, $(DEMO_MOVEMENT_DIR)%.o, $(DEMO_MOVEMENT_SOURCES))

# - DEMO - MANIPULATION FILES -
DEMO_MANIPULATION_SOURCES=$(DEMO_MANIPULATION_DIR)main.cpp
DEMO_MANIPULATION_OBJECTS=$(patsubst $(DEMO_MANIPULATION_DIR)%.cpp, $(DEMO_MANIPULATION_DIR)%.o, $(DEMO_MANIPULATION_SOURCES))

# - TEST FILES -
TEST_SOURCES=$(TEST_DIR)main.cpp
TEST_OBJECTS=$(patsubst $(TEST_DIR)%.cpp, $(TEST_DIR)%.o, $(TEST_SOURCES))

# - UNIT TEST FILES -
UNITTEST_SOURCES=$(UNITTEST_DIR)$(NAME)-Test-API.cpp $(UNITTEST_DIR)$(NAME)-Test-Vectors.cpp $(UNITTEST_DIR)$(NAME)-Test-Scalars.cpp $(UNITTEST_DIR)$(NAME)-Test-Main.cpp
UNITTEST_OBJECTS=$(patsubst $(UNITTEST_DIR)%.cpp, $(UNITTEST_DIR)%.o, $(UNITTEST_SOURCES))

# - OUTPUT FILES -

# - G++ -
CORE_F=$(LIB_DIR)$(NAME)
DLL_LINK_LIB=$(LIB_DIR)lib$(NAME).dll.a

KINECT_MS_LIB=$(LIB_DIR)$(NAME)-Kinect-MS.lib

DEMO_SLIDESHOW_EXE=Bin/Demo-Slideshow.exe
DEMO_MOVEMENT_EXE=Bin/Demo-Movement.exe
DEMO_MANIPULATION_EXE=Bin/Demo-Manipulation.exe

TEST_EXE=$(BIN_DIR)Test.exe
UNITTEST_EXE=$(BIN_DIR)UnitTests.exe

# - LIBRARIES -

KINECT_DIR='$(subst \,/,$(KINECTSDK10_DIR))'
CV_DIR='$(subst \,/,$(OPENCV_DIR))'
CV_LIB_DIR=$(CV_DIR)build/x86/mingw/bin/libopencv_
THIRD_PARTY_LIBS=-lKinect10 -lopencv_core241.dll -lopencv_highgui241.dll -lopencv_imgproc241.dll -lopencv_objdetect241.dll
LIBS=$(CORE_F).lib $(KINECT_MS_LIB)
UNITTEST_LIB=../UnitTest++/UnitTest.lib

# - TOOLS -

CC=g++ -DGPLUSPLUS
COPY=cp
RM=rm

# - FLAGS -

INCLUDE_FLAGS=-I $(INC_DIR) -I $(INC_DIR)Win32 -I $(KINECT_DIR)inc -I $(CV_DIR)build/include
LIB_FLAGS=-L $(CV_DIR)build/x86/mingw/lib/ -L $(KINECT_DIR)lib/x86/
CFLAGS=-DBUILD -DVISUAL -std=c++0x -c -g -Wall $(INCLUDE_FLAGS)
DLL_FLAGS=-shared -Wl,--out-implib,$(DLL_LINK_LIB),--output-def,$(CORE_F).dll.def $(LIB_FLAGS)

#LIBRARIES=$(CORE_F).lib $(KINECT_MS_LIB)
LIBRARIES=$(DLL_LINK_LIB)

# - TARGETS - 
clean:
	$(RM) \
	       	$(CORE_OBJECTS) \
	       	$(KINECT_MS_OBJECTS) \
		$(DEMO_SLIDESHOW_OBJECTS) \
		$(DEMO_MOVEMENT_OBJECTS) \
		$(DEMO_MANIPULATION_OBJECTS) \
		$(TEST_OBJECTS) \
		$(UNITTEST_OBJECTS) \
		$(LIB_DIR)*.def \
		$(LIB_DIR)*.a \
		$(CORE_F).dll \
		$(CORE_F).lib \
		$(KINECT_MS_LIB) \
		$(BIN_DIR)*.exe
	 
# - G++ -

# --------------- FILES -----------
# - GENERIC -
%.o: %.cpp
	$(CC) $(CFLAGS) -o $@ $< 

# - STATIC LIBRARIES -
$(CORE_F).lib: $(CORE_OBJECTS) 
	ar crf $@ $^
$(KINECT_MS_LIB): $(KINECT_MS_OBJECTS)
	ar crf $@ $^
# - DYNAMIC LIBRARIES -
$(CORE_F).dll: $(CORE_OBJECTS) $(KINECT_MS_OBJECTS)
	$(CC) $(DLL_FLAGS) -o $@ $^ $(THIRD_PARTY_LIBS)
	$(COPY) -f $(CORE_F).dll $(BIN_DIR)
$(CORE_F).a: $(CORE_F).dll
$(DLL_LINK_LIB): $(CORE_F).dll

# - DEMOS -
$(DEMO_SLIDESHOW_EXE): $(DEMO_SLIDESHOW_OBJECTS) $(LIBRARIES)
	$(CC) $(LIB_FLAGS) -o $@ $^ $(THIRD_PARTY_LIBS)
$(DEMO_MOVEMENT_EXE): $(DEMO_MOVEMENT_OBJECTS) $(LIBRARIES)
	$(CC) $(LIB_FLAGS) -o $@ $^ $(THIRD_PARTY_LIBS)
$(DEMO_MANIPULATION_EXE): $(DEMO_MANIPULATION_OBJECTS) $(LIBRARIES)
	$(CC) $(LIB_FLAGS) -o $@ $^ $(THIRD_PARTY_LIBS)
# - TESTS -
$(TEST_EXE): $(TEST_OBJECTS) $(LIBRARIES)
	$(CC) $(LIB_FLAGS) -o $@ $^ $(THIRD_PARTY_LIBS)
$(UNITTEST_EXE): $(UNITTEST_OBJECTS) $(LIBRARIES)
	$(CC) $(LIB_FLAGS) -o $@ $^ $(UNITTEST_LIB) $(THIRD_PARTY_LIBS)

# --------------  FINAL --------------

# ------- COMPILE ------- 
# - CORE -
COMPILE_CORE: $(CORE_OBJECTS)
COMPILE_CORE_V: $(CORE_OBJECTS)
COMPILE_CORE_D: $(CORE_OBJECTS)
COMPILE_CORE_DV: $(CORE_OBJECTS)
# - KINECT MS -
COMPILE_KINECT_MS: $(KINECT_MS_OBJECTS)
COMPILE_KINECT_MS_V: $(KINECT_MS_OBJECTS)
COMPILE_KINECT_MS_D: $(KINECT_MS_OBJECTS)
COMPILE_KINECT_MS_DV: $(KINECT_MS_OBJECTS)
# - TESTS -
COMPILE_TEST: $(TEST_OBJECTS)
COMPILE_UNIT: $(UNITTEST_OBJECTS)
# - DEMOS -
COMPILE_DEMO_SLIDESHOW: COMPILE_CORE $(DEMO_SLIDESHOW_OBJECTS)
COMPILE_DEMO_MOVEMENT: COMPILE_CORE $(DEMO_MOVEMENT_OBJECTS)
COMPILE_DEMO_MANIPULATION: COMPILE_CORE $(DEMO_MANIPULATION_OBJECTS)
COMPILE_DEMOS: DEMO_SLIDESHOW DEMO_MOVEMENT DEMO_MANIPULATION
# - FULL -
COMPILE: COMPILE_API COMPILE_KINECT_MS COMPILE_TEST COMPILE_UNIT DEMOS
COMPILE_V: COMPILE_API_V COMPILE_KINECT_MS_V COMPILE_TEST COMPILE_UNIT DEMOS
COMPILE_D: COMPILE_API_D COMPILE_KINECT_MS_D COMPILE_TEST COMPILE_UNIT DEMOS
COMPILE_DV: COMPILE_API_DV COMPILE_KINECT_MS_DV COMPILE_TEST COMPILE_UNIT DEMOS

# ------- LINK -------
# - CORE -
LIB_CORE: $(CORE_F).lib
DLL: $(CORE_F).dll
# - MS -
LIB_KINECT_MS: $(KINECT_MS_LIB)
# - BOTH -
LIB: LIB_CORE LIB_KINECT_MS
# - TEST -
TEST: $(TEST_EXE) 
UNIT: $(UNITTEST_EXE)
# - DEMOS -
DEMO_SLIDESHOW: $(DEMO_SLIDESHOW_EXE)
DEMO_MOVEMENT: $(DEMO_MOVEMENT_EXE)
DEMO_MANIPULATION: $(DEMO_MANIPULATION_EXE)
DEMOS: DEMO_SLIDESHOW DEMO_MOVEMENT DEMO_MANIPULATION

# ------- RUN -------
TEST_RUN: TEST
	$(TEST_EXE)
UNIT_RUN: UNIT
	$(UNITTEST_EXE)
DEMO_SLIDESHOW_RUN: DEMO_SLIDESHOW
	$(DEMO_SLIDESHOW_EXE) Img/1.jpg Img/2.jpg Img/3.jpg Img/4.jpg Img/5.jpg Img/6.jpg
DEMO_MOVEMENT_RUN: DEMO_MOVEMENT
	$(DEMO_MOVEMENT_EXE)
DEMO_MANIPULATION_RUN: DEMO_MANIPULATION
	$(DEMO_MANIPULATION_EXE)

# - MSVC
$(CORE_LIB_MS): $(CORE_DEF)
	lib /machine:i386 /def:$<
$(TEST_EXE_MS): $(CORE_LIB_MS)
	cl /I $(INC_DIR) /I "C:\Program Files\Microsoft SDKs\Kinect\v1.0\inc" Main.cpp $^
	


all: DLL
